name: Deploy React.js with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      
      - name: Update and upgrade server packages
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get update -y
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get upgrade -y
      
      
    
      - name: Set up PostgreSQL
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install postgresql -y
      
      - name: Connect PostgreSQL 
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install postgresql-client -y
     
      - name: Connect to PostgreSQL database
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S -u postgres psql -U 'mohid' -d 'invozone' -W '123456'
      
     
      - name: Install Node.js
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt install nodejs -y
    
      - name: install npm 
        run: |
           cd  /home/ali/
           echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt install npm -y
            
      - name: create react app
        run: | 
           cd /home/ali
           npx create-react-app reactapp
    
      - name: Build the React.js application
        run: |
           cd /home/ali/reactapp 
           npm run build
              
            
      - name: Deploy to server
        run: |
          cp -r /home/ali/reactapp/build/* /var/www/html/IZ
          
      - name: restart nginx
        run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
