name: Create Folder Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_folder:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Create Folder
      run: mkdir /root/mohid/ali
    
   


    - name: Commit and push changes
      run: |
        git config --global user.name 'maatique'
        git config --global user.email 'mohid.ali@invozone.com'
        git add .
        git commit -m 'Create folder'
        git push
