name: Create Folder Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_folder:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Setup SSH
      run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    
    - name: Add host key to known_hosts
      run: ssh-keyscan -t rsa root@157.245.86.84 >> ~/.ssh/known_hosts


    - name: Commit and push changes
      run: |
        git config --global user.name 'maatique'
        git config --global user.email 'mohid.ali@invozone.com'
        git add .
        git commit -m 'Create folder'
        git push
