name: Create Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: sync HTML
      run:  rsync -avz  /home/ali/actions-runner/_work/IZ/IZ
                          /var/www/html/
   
    - name: Restart Nginx
      run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
