name: Create File Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_folder:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Create Folder
      run:  touch /home/mohid/file.txt
   
