name: Create File Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_folder:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Create Folder
      run: sudo touch /root/file.txt
    
   


    - name: Commit and push changes
      run: |
        git add .
        git commit -m 'Create file'
        git push
