name: Create Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy HTML files
      run:  
          sudo cp -r . /var/www/html/

    - name: Restart Nginx
      run: sudo service nginx restart
