name: Create Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: sync HTML
      run:  rsync -avz /var/www/html/IZ/index.nginx-debian.html
   
    - name: Restart Nginx
      run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
