name: Deploy React.js with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install NPM
        run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S sudo apt-get install npm -y

      - name: Install dependencies
        run:  npm ci

      - name: Build application
        run:  npm run build

      - name: Set up PostgreSQL
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S sudo apt-get update -y
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S sudo apt-get install postgresql -y


      - name: Set up PostgreSQL client
        run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install postgresql-client -y

      - name: Create PostgreSQL database
        run: |
          psql -c "CREATE DATABASE invozone;"
          psql -c "CREATE USER mohid WITH ENCRYPTED PASSWORD '123456';"
          psql -c "GRANT ALL PRIVILEGES ON DATABASE invozone TO mohid;"

      - name: Deploy to server
        run: |
          # Copy the build files to your server (e.g., using SCP or FTP)
          # Run any necessary scripts to start your React.js application on the server
