name: Deploy React.js with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update and upgrade server packages
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get update -y
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get upgrade -y

      - name: Install Node.js and npm
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt install nodejs -y
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt install npm -y

      - name: Install project dependencies
        run: npm install

      - name: Set up PostgreSQL
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install postgresql -y

      - name: Set up PostgreSQL client
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install postgresql-client -y

     
      - name: Connect to PostgreSQL database
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S -u postgres psql -h '157.230.60.4' -p '22' -U 'mohid' -d 'invozone' -W '123456'
          

      - name: Build the React.js application
        run: npm run build

      - name: Deploy to server
        run: |
          # Copy the build files to your server (e.g., using SCP or FTP)
          # Run any necessary scripts to start your React.js application on the server
