name: Deploy Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
            
    - name: sync HTML
      run:  rsync -avz /var/www/html/IZ/mohid.html

    - name: Restart Nginx
      run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
