name: Deploy Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
            
    - name: sync HTML
      run:  rsync -avz /home/ali/actions-runner/_work/IZ/IZ/index.nginx-debian.html /var/www/html/IZ

    - name: Restart Nginx
      run:  echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
